name: pixx

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports: 
      - "5432:5432"
    volumes:
      - ./pixx_db_data:/var/lib/postgresql/data

# web: